# Generated by Django 6.0.2 on 2026-02-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_usario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='usario',
            new_name='usuario',
        ),
    ]
