# Generated by Django 6.0.2 on 2026-03-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_rename_usario_paciente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('Tarjeta de identidad', 'Tarjeta de identidad'), ('Pasaporte', 'Pasaporte'), ('Cedula de extranjeria', 'Cédula de extranjería'), ('Cedula de ciudadania', 'Cédula de ciudadanía')], max_length=30),
        ),
    ]
