# Generated by Django 6.0.2 on 2026-03-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias_clinicas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiaclinica',
            old_name='antecedentes',
            new_name='alergias',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='antecedentes_medicos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='medicamentos_actuales',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='motivo_consulta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
