# Generated by Django 6.0.2 on 2026-03-31 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias_clinicas', '0002_rename_antecedentes_historiaclinica_alergias_and_more'),
        ('pacientes', '0003_rename_usario_paciente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias', to='pacientes.paciente'),
        ),
    ]
