# Generated by Django 6.0.2 on 2026-02-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('psicologo', 'Psicólogo'), ('paciente', 'Paciente'), ('recepcion', 'Recepción')], max_length=20),
        ),
    ]
