# Generated by Django 6.0.2 on 2026-03-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_recuperacionpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recuperacionpassword',
            old_name='fecha_creacion',
            new_name='creado_en',
        ),
        migrations.AlterField(
            model_name='recuperacionpassword',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
    ]
