# Generated by Django 6.0.2 on 2026-02-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('pacientes', '0002_paciente_usario'),
        ('psicologos', '0002_psicologo_usuario'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(fields=('psicologo', 'fecha', 'hora'), name='cita_unica_psicologo_fecha_hora'),
        ),
    ]
