# Generated by Django 6.0.2 on 2026-02-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_cita_unica_psicologo_fecha_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='atendida_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='motivo_cancelacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
