# Generated by Django 6.0.2 on 2026-02-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologos', '0003_horariopsicologo'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='duracion_cita_min',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
